### PR TITLE
Jason fix build rand issues

### PR DESCRIPTION
**Pull request by jmkim2392**
resolved build issues and changed rand to not generate same every time (lol)

### CODE REVIEW

**Review by dstrigoun — COMMENTED** [review]
On line 38 of Main.cpp, can you remove the forward declaration of WndProc since it's in the header file?

**Comment by jmkim2392** [comment]
removed WndProc forward dec, sry im such a mess
i should probably move those static values to header file as well?

**Comment by dstrigoun** [comment]
No worries! Also this is really minor but it would be nice if we just put all the import statements in `Main.h` and just import that header file in `Main.cpp`.

**Comment by dstrigoun** [comment]
Sorry didn't see your update, having the static values in the header file would be nice!

**Comment by jmkim2392** [comment]
Good call, changed as requested

**Comment by dstrigoun** [comment]
Did moving the random generator fix that bug?

**Comment by jmkim2392** [comment]
yes, the starting will always be only incrementally different based on the time it was first seeded, 
but the following numbers generated after are randomized and are not the same as the initial value

**Review by dstrigoun — APPROVED** [review]
Ah, I see. Okay this looks good to me!

**Pull request merged**
