### PR TITLE
CRC (dummy)

### PR DESCRIPTION
**Pull request by dstrigoun**
This will just append a dummy CRC bit (i.e. `1`) to the end of a frame in a hard coded way. This is just for testing purposes while the mechanics of CRC get figured out. All the code that is not being used has been commented out for future purposes.

I suspect that in order to build this everyone will have to have a library downloaded.. Not totally sure..
Here's the link to the Boost c++ library downloads page for version 1.68.0: https://www.boost.org/users/history/version_1_68_0.html

### CODE REVIEW

**Review by jmkim2392 — COMMENTED** [review]
Everything looks okay to me, I'm just installing boost right now to test.
Will approve once i test its working.
Good job!

**Comment by jmkim2392** [comment]
I think i'm having issues trying to install boost. 
Could you provide a quick guide on how?

**Comment by dstrigoun** [comment]
@jmkim2392 @KieranQLee @PikAleex - Here are the instructions on installing Boost.

1. Download Boost v 1.68.0 using this link: https://www.boost.org/users/history/version_1_68_0.html
2. Extract the zip file to `C:/ProgramFiles (x86)`
3. In Visual Studio, go to Project Properties
4. Go to C/C++ > General
5. Add a directory to "Additional Include Directories"
6. Click on the browse (...) button to select the boost folder in `C:\ProgramFiles (x86)`
7. Apply changes to project

That should get rid of any errors when trying to build the project.

**Comment by jmkim2392** [comment]
Thx I'll try it now and update!

**Review by jmkim2392 — APPROVED** [review]
Looks good just need to resolve merge conflicts

**Pull request merged**
