### PR TITLE
attempt at Receive-timeout. the isReceiving could be isListening?

### PR DESCRIPTION
**Pull request by PikAleex**

### CODE REVIEW

**Review by jmkim2392 — COMMENTED** [review]
I think we might have to revisit how we want to do this. 
My understanding of event driven approach is still very shallow, but this will definitely need refactoring based on approval of my other branch. 

Also, I think we need to discuss if its viable to mix the state transitions within the thread. 
It might be better to simply close and start a new thread with a new thread function designed for that state.

**Comment by PikAleex** [comment]
So what you're thinking is that we should have a separate thread that will constantly check for certain flags and change states accordingly?

**Comment by jmkim2392** [comment]
No, I think when the states change, it should automatically terminate our current idle State thread, and we should start a new receive State thread

**Comment by PikAleex** [comment]
oh okay so every state has a thread that will have their own things accordingly

**Comment by jmkim2392** [comment]
I'm not sure, but i think that's a good idea and easier to manage. We should talk it over tomorrow.
This way might lead to a lot of code dupes, but the other will be a big thread function with a switch statement. I think. We can check which one is easier to implement and works better

**Pull request closed without merging**
